export interface Product {
    id: string;
    name: string;
    brand: string;
    price: string;
    rating: number;
    reviews: string;
    retailer: string;
    image: string;
    colorname: string;
    colortag: string;
    colorid: string;
    shipping?: string;
  }
  //Possible Accumulators: Total Price of Inventory, Average Rating for Each color, List of Retailers for Each Color, Products with Highest and lowest price for each color
  // Sample products with multiple color tags
  export const LIPSTICK_PRODUCTS: Product[] = [
    {
      id: 'ls1',
      name: 'Audacious - Carmen',
      brand: 'NARS Cosmetics',
      price: '$45.00',
      rating: 4.5,
      reviews: '(9k+)',
      retailer: 'Sephora',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Berry',
      colortag: '#800000',
      colorid: '4',
    },
    {
      id: 'ls2',
      name: 'Rosso Valentino High Pigment',
      brand: 'Valentino',
      price: '$45.00',
      rating: 4.5,
      reviews: '(441)',
      retailer: 'Sephora',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Pink',
      colortag: '#FF69B4',
      colorid: '1',
    },
    {
      id: 'ls3',
      name: 'Rouge Dior Forever Transfer-Proof',
      brand: 'Dior',
      price: '$47.00',
      rating: 4.5,
      reviews: '(9k+)',
      retailer: 'Sephora',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Coral',
      colortag: '#FF4500',
      colorid: '5',
    },
    {
      id: 'ls4',
      name: 'MAC - Retro Matte Lipstick - Ruby Woo',
      brand: 'MAC Cosmetics',
      price: '$23.00',
      rating: 4.5,
      reviews: '(9k+)',
      retailer: 'MAC Cosmetics',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Red',
      colortag: '#FF0000',
      colorid: '3',
    },
    {
      id: 'ls5',
      name: 'Charlotte Tilbury K.I.S.S.I.N.G Satin',
      brand: 'Charlotte Tilbury',
      price: '$35.00',
      rating: 4.5,
      reviews: '(4k+)',
      retailer: 'Sephora',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Nude',
      colortag: '#FFE4C4',
      colorid: '2',
    },
    {
      id: 'ls6',
      name: 'Revlon Super Lustrous Lipstick',
      brand: 'Revlon',
      price: '$6.49',
      rating: 4.5,
      reviews: '(9k+)',
      retailer: 'Target',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Coral',
      colortag: '#FF4500',
      colorid: '5',
    },
    {
      id: 'ls7',
      name: 'NARS Lipstick, Jungle Red',
      brand: 'NARS Cosmetics',
      price: '$26.00',
      rating: 4.5,
      reviews: '(9k+)',
      retailer: 'NARS Cosmetics',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Berry',
      colortag: '#800000',
      colorid: '4',
    },
    {
      id: 'ls8',
      name: 'Matte Lipsticks - Loving Red',
      brand: 'Walmart',
      price: '$16.99',
      shipping: 'Free shipping',
      rating: 4.5,
      reviews: '(9k+)',
      retailer: 'Walmart',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Pink',
      colortag: '#FF69B4',
      colorid: '1',
    },
    {
      id: 'ls9',
      name: 'Lipstick Red & Blue - Red With Blue',
      brand: 'Byredo',
      price: '$55.00',
      shipping: 'Free shipping',
      rating: 4.5,
      reviews: '(9k+)',
      retailer: 'Byredo.com',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Blue',
      colortag: '#0000FF',
      colorid: '6', // Adjusted example
    },
    {
      id: 'ls10',
      name: 'Pillow Talk Original',
      brand: 'Charlotte Tilbury',
      price: '$34.00',
      rating: 4.8,
      reviews: '(12k+)',
      retailer: 'Sephora',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Nude',
      colortag: '#FFE4C4',
      colorid: '2',
    },
    {
      id: 'ls11',
      name: 'Velvet Teddy',
      brand: 'MAC',
      price: '$21.00',
      rating: 4.7,
      reviews: '(15k+)',
      retailer: 'MAC',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Nude',
      colortag: '#FFE4C4',
      colorid: '2',
    },
    {
      id: 'ls12',
      name: 'Les Beiges Natural Nude',
      brand: 'CHANEL',
      price: '$45.00',
      rating: 4.6,
      reviews: '(8k+)',
      retailer: 'CHANEL',
      image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=100&q=80',
      colorname: 'Nude',
      colortag: '#FFE4C4',
      colorid: '2',
    },
  ];
  